language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

install:
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - pip install -r requirements-dev.txt

script:
  - make lint
  - make test
  - make coverage

after_success:
  coveralls
